# Clash Verge DNS Config
dns:                                     # DNS覆写
  enable: true                           # DNS解析
  listen: :53                            # DNS监听地址
  enhanced-mode: fake-ip                 # Mihomo的DNS处理模式 [fake-ip/redir-host]
  fake-ip-range: 198.18.0.1/16           # Fake IP范围
  fake-ip-filter-mode: blacklist         # Fake IP过滤模式 [blacklist/whitelist]
  ipv6: false                            # IPv6 DNS解析
  prefer-h3: false                       # DNS DOH使用HTTP/3协议
  respect-rules: false                   # DNS链接遵循路由规则
  use-hosts: true                        # 通过Host文件解析域名
  use-system-hosts: true                 # 通过系统 Host 文件解析域名
  direct-nameserver-follow-policy: false # 直连域名服务器遵循策略
  # 默认域名服务器, 用于解析DNS服务器的默认DNS服务器
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  # 默认的域名解析服务器
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  # 后备域名解析服务器
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  # 代理节点域名解析服务器
  proxy-server-nameserver:
  - 119.29.29.29
  - https://dns.google/dns-query
  # 直连出口域名解析的DNS服务器
  direct-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  # Fake IP过滤
  fake-ip-filter:
  - '+.lan'
  - '+.local'
  - '+.localhost'
  # Microsoft
  - 'time.windows.com'
  - '+.msftconnecttest.com'
  - '+.msftncsi.com'
  - '+.microsoft.com'
  - '+.windowsupdate.com'
  - '+.xboxlive.com'
  # Apple
  - '+.apple.com'
  - '+.icloud.com'
  - '+.itunes.com'
  - '+.appstore.com'
  # GeoSite
  - 'geosite:connectivity-check'
  - 'geosite:private'
  - 'geosite:cn'
  - '!geosite:category-games@cn'
  # 指定域名查询的解析服务器
  nameserver-policy:
    geosite:cn,private:
    - 119.29.29.29
    - 223.5.5.5
  fallback-filter: # 后备域名解析服务器筛选
    geoip: true    # GeoIP回退过滤
    geoip-code: CN # GeoIP国家代码
    ipcidr:        # 回退IP CIDR [网段已经污染]
    - 240.0.0.0/4
    - 0.0.0.0/32
    domain:        # 回退域名 [域名已经污染]
    - +.google.com
    - +.youtube.com
    - +.github.com
    - +.telegram.org
hosts: {}
