# Clash Verge DNS Config
# @MengZiJun0262

hosts: []

DNS_CN                           : &DNS_CN                   223.5.5.5, 119.29.29.29
DOH_CN                           : &DOH_CN                   https://dns.alidns.com/dns-query, https://doh.pub/dns-query
DNS_FOREIGN                      : &DNS_FOREIGN              8.8.8.8, 1.1.1.1
DOH_FOREIGN                      : &DOH_FOREIGN              https://dns.google/dns-query, https://cloudflare-dns.com/dns-query

dns                              :                           # DNS覆写
  enable                         : true                      # DNS解析
  listen                         : :53                       # DNS监听地址
  enhanced-mode                  : fake-ip                   # Mihomo的DNS处理模式
  fake-ip-range                  : 198.18.0.1/16             # Fake IP范围
  fake-ip-filter-mode            : blacklist                 # Fake IP过滤模式
  ipv6                           : false                     # IPv6 DNS解析
  prefer-h3                      : false                     # DNS DOH使用HTTP/3协议
  respect-rules                  : false                     # DNS链接遵循路由规则
  use-hosts                      : true                      # 通过Host文件解析域名
  use-system-hosts               : true                      # 通过系统 Host 文件解析域名
  direct-nameserver-follow-policy: false                     # 直连域名服务器遵循策略
  default-nameserver             : [*DNS_CN]                 # 解析DNS服务器的默认域名服务器
  proxy-server-nameserver        : [*DOH_CN]                 # 代理节点域名解析服务器
  direct-nameserver              : [*DOH_CN]                 # 直连出口域名解析的DNS服务器
  nameserver                     : [*DOH_FOREIGN]            # 默认的域名解析服务器
  fallback                       : [*DOH_FOREIGN]            # 后备域名解析服务器
  fallback-filter                :                           # 后备域名解析服务器筛选
    geoip                        : true                      # GeoIP回退过滤
    geoip-code                   : CN                        # GeoIP国家代码
    ipcidr                       : [240.0.0.0/4, 0.0.0.0/32] # 回退IP CIDR
    domain                       : []                        # 回退域名
  nameserver-policy              : []                        # 指定域名查询的解析服务器
  fake-ip-filter                 :
#LAN
  - "*"
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - "*.direct"
#放行NTP服务
  - "time.*.com"
  - "time.*.gov"
  - "time.*.edu.cn"
  - "time.*.apple.com"
  - "time-ios.apple.com"
  - "time1.*.com"
  - "time2.*.com"
  - "time3.*.com"
  - "time4.*.com"
  - "time5.*.com"
  - "time6.*.com"
  - "time7.*.com"
  - "ntp.*.com"
  - "ntp1.*.com"
  - "ntp2.*.com"
  - "ntp3.*.com"
  - "ntp4.*.com"
  - "ntp5.*.com"
  - "ntp6.*.com"
  - "ntp7.*.com"
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - "time1.cloud.tencent.com"
#放行网易云音乐
  - "music.163.com"
  - "*.music.163.com"
  - "*.126.net"
#百度音乐
  - "musicapi.taihe.com"
  - "music.taihe.com"
#酷狗音乐
  - "songsearch.kugou.com"
  - "trackercdn.kugou.com"
#酷我音乐
  - "*.kuwo.cn"
#JOOX音乐
  - "api-jooxtt.sanook.com"
  - "api.joox.com"
  - "joox.com"
#QQ音乐
  - "y.qq.com"
  - "*.y.qq.com"
  - "streamoc.music.tc.qq.com"
  - "mobileoc.music.tc.qq.com"
  - "isure.stream.qqmusic.qq.com"
  - "dl.stream.qqmusic.qq.com"
  - "aqqmusic.tc.qq.com"
  - "amobile.music.tc.qq.com"
#虾米音乐
  - "*.xiami.com"
#咪咕音乐
  - "*.music.migu.cn"
  - "music.migu.cn"
#win10本地连接检测
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
#QQ登录
  - "localhost.ptlogin2.qq.com"
  - "localhost.sec.qq.com"
#微信登录
  - "localhost.*.weixin.qq.com"
  - "+.kk-rays.com"
#Game
#Steam
  - "+.steamcontent.com"
#Nintendo Switch
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.cdn.nintendo.net"
#Microsoft Xbox
  - "xbox.*.*.microsoft.com"
  - "*.*.xboxlive.com"
  - "xbox.*.microsoft.com"
  - "xnotify.xboxlive.com"
#Wotgame
  - "+.battle.net"
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
#Golang
  - "proxy.golang.org"
#STUN
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "myip.addr.tools"
#Linksys Router
  - "heartbeat.belkin.com"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
#ASUS Router
  - "*.router.asus.com"
#Apple Software Update Service
  - "mesu.apple.com"
  - "swscan.apple.com"
  - "swquery.apple.com"
  - "swdownload.apple.com"
  - "swcdn.apple.com"
  - "swdist.apple.com"
#Google
  - "lens.l.google.com"
  - "na.b.g-tun.com"
#FinalFantasy XIV Worldwide Server & CN Server
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - "ff.dorado.sdo.com"
#Bilibili
  - "*.mcdn.bilivideo.cn"
#Disney Plus
  - "+.media.dssott.com"
#shark007 Codecs
  - "shark007.net"
#Mijia
  - "Mijia.Cloud"
#Xiaomi
  - "+.market.xiaomi.com"
#招商银行
  - "+.cmbchina.com"
  - "+.cmbimg.com"
#AdGuard
  - "adguardteam.github.io"
  - "adrules.top"
  - "anti-ad.net"
  - "local.adguard.org"
  - "static.adtidy.org"
#迅雷
  - "+.sandai.net"
  - "+.n0808.com"
#T-mobile and Ultra Mobile wifi calling
  - "+.3gppnetwork.org"
#UU Plugin
  - "+.uu.163.com"
  - "ps.res.netease.com"
#Wifi Calling
  - "+.pub.3gppnetwork.org"
#向日葵远程控制
  - "+.oray.com"
  - "+.orayimg.com"
#LOL语音
  - "+.gcloudcs.com"
  - "+.gcloudsdk.com"
#ddns
  - "+.dynv6.net"
