# Clash Verge DNS Config

DNS_CN        : &DNS_CN      223.5.5.5
DOH_CN        : &DOH_CN      https://dns.alidns.com/dns-query, https://doh.pub/dns-query
DNS_FOREIGN   : &DNS_FOREIGN 8.8.8.8
DOH_FOREIGN   : &DOH_FOREIGN https://dns.google/dns-query, https://cloudflare-dns.com/dns-query

dns                              :                          # DNS覆写
  enable                         : true                     # DNS解析
  listen                         : :53                      # DNS监听地址
  enhanced-mode                  : fake-ip                  # Mihomo的DNS处理模式
  fake-ip-range                  : 198.18.0.1/16            # Fake IP范围
  fake-ip-filter-mode            : blacklist                # Fake IP过滤模式
  ipv6                           : false                    # IPv6 DNS解析
  prefer-h3                      : false                    # DNS DOH使用HTTP/3协议
  respect-rules                  : false                    # DNS链接遵循路由规则
  use-hosts                      : true                     # 通过Host文件解析域名
  use-system-hosts               : true                     # 通过系统 Host 文件解析域名
  direct-nameserver-follow-policy: false                    # 直连域名服务器遵循策略
  default-nameserver             : [*DNS_CN]                # 解析DNS服务器的默认域名服务器
  proxy-server-nameserver        : [*DOH_CN]                # 代理节点域名解析服务器
  direct-nameserver              : [*DOH_CN]                # 直连出口域名解析的DNS服务器
  nameserver                     : [*DOH_FOREIGN]           # 默认的域名解析服务器
  fallback                       : [*DOH_FOREIGN]           # 后备域名解析服务器
  fallback-filter                :                          # 后备域名解析服务器筛选
    geoip                        : true                     # GeoIP回退过滤
    geoip-code                   : CN                       # GeoIP国家代码
    ipcidr                       : [240.0.0.0/4,0.0.0.0/32] # 回退IP CIDR
    domain                       : []                       # 回退域名
  nameserver-policy              : []                       # 指定域名查询的解析服务器
#  fake-ip-filter:
#    - "rule-set:fakeipfilter_domain"
hosts: []
